In [2]:
import numpy as np
print(np.__version__)

1.18.2


#create a 1D array

In [4]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#create a boolean array

In [8]:
bo1=np.full((3, 3), True, dtype=bool)
print(bo1)
# Alternate method:
bo2=np.ones((3,3), dtype=bool)
print(bo2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Extract all odd numbers from arr

In [9]:
# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1


In [15]:
arr[arr % 2 == 1] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#to reshape an array

In [16]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#to stack two arrays vertically

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


#to stack two arrays horizontally 

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Method 1:
np.concatenate([a, b], axis=1)
# Method 2:
np.hstack([a, b])
# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#Create the following pattern without hardcoding

In [26]:
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#Get the common items between a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

#From array a remove all items present in array b

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

#Get the positions where elements of a and b match

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

#to extract all numbers between a given range

In [33]:
#Get all items between 5 and 10 from a
a = np.arange(15)
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

#Convert the function maxx that works on two scalars, to work on two arrays.

In [34]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

#Swap columns 1 and 2 in the array

In [37]:
arr = np.arange(9).reshape(3,3)
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#to swap two rows in a 2d

In [38]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#to reverse the rows of a 2D

In [39]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#to reverse the columns of a 2D

In [40]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

#2D array of shape 5×3 to contain random decimal numbers between 5 and 10.

In [41]:

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[5.66994321 5.73548352 8.83743621]
 [9.40722956 6.49749487 9.82265455]
 [6.61083447 8.67986284 7.24393776]
 [6.47301914 8.61414347 5.21910991]
 [8.39049455 6.23506813 9.5906887 ]]


#show only 3 decimal places

In [42]:
# Input
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.051, 0.756, 0.681],
       [0.809, 0.153, 0.585],
       [0.458, 0.162, 0.276],
       [0.433, 0.499, 0.406]])

#print rand_arr by suppressing the scientific notation (like 1e10)

In [44]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

#Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [49]:

np.set_printoptions(threshold=6)
a = np.arange(15)
a


array([ 0,  1,  2, ..., 12, 13, 14])

#to print the full numpy array without truncating

In [59]:
# Input
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#Import the iris dataset keeping the text intact

In [60]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)